apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc
  namespace: media  
  labels:
    app: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  volumeName: jellyfin-pv
  resources:
    requests:
      storage: 500Gi  
