apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-config-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: jellyfin-config-pv
    volumeAttributes:
      server: 10.0.0.231
      share: /mnt/kadal/apps
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-movies-pv
spec:
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: jellyfin-movies-pv
    volumeAttributes:
      server: 10.0.0.231
      share: /mnt/kadal/media/movies
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-shows-pv
spec:
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: jellyfin-shows-pv
    volumeAttributes:
      server: 10.0.0.231
      share: /mnt/kadal/media/shows
