apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tvm
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/chandiroor
      sourceRef:
        kind: GitRepository
        name: tvm   # overridden per overlay
  values: {}        # overridden per overlay
