apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab-gitops
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/kamalnathvg/homelab
  ref:
    branch: main
