apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tvm
  namespace: flux-system
  annotations:
    image.toolkit.fluxcd.io/update: auto
spec:
  interval: 5m
  targetNamespace: default
  chart:
    spec:
      chart: ./charts/tvm
      sourceRef:
        kind: GitRepository
        name: homelab-gitops
  values:
    image:
      repository: kamalnathvg/tvm
      tag: "kamalnathvg/tvm:2026.06.29.4" # {"$imagepolicy": "flux-system:tvm"}
