apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-stack-pvc
  namespace: monitoring  
  labels:
    app: kube-prometheus-stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 50Gi  
