# overlays/dev/imagepolicy.yaml
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: chandiroor-release
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: chandiroor-release
  filterTags:
    pattern: '^rc-\d{4}\.\d{2}\.\d{2}\.\d+$'   # only dev-YYYY.MM.DD.NNN tags
  policy:
    alphabetical:
      order: asc
