apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyseerr-config-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: jellyseerr-config-pv
    volumeAttributes:
      server: 10.0.0.231
      share: /mnt/kadal/apps/jellyseerr
