apiVersion: v1
kind: Service
metadata:
  name: {{ include "panchangam-api.fullname" . }}
  labels:
    {{- include "panchangam-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- with .Values.service.nodePort}}
      nodePort: {{ . }}
      {{ end }}
      protocol: TCP
      name: http
  selector:
    {{- include "panchangam-api.selectorLabels" . | nindent 4 }}
